### ISSUE TITLE
Image no longer works

### ISSUE THREAD

**Issue by strowk** [dbsystel/postgresql-partman-container#20] opened 2024-11-13 12:58 UTC
Running this
```
docker run -ti -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=testpwd  ghcr.io/dbsystel/postgresql-partman:15-4
```
results in 
`/opt/bitnami/scripts/libpostgresql.sh: line 395: POSTGRESQL_REPLICATION_USE_PASSFILE: unbound variable`. It seems that there was some issue in underlying bitnami image. Please consider updating/pinning to version without this bug. Thanks

**Comment by strowk** [comment] 2024-11-13 13:12
Please also consider pinning upstream version. Bitnami seems to tage them like 15.4.0-debian-11-r50 15.4.0-debian-11-r51 . It would be much stable if you could use those tags to pin version, run some sort of test in CI before publishing the build and setup periodic version update using f.e dependabot. This would achieve the same automatic update process, but without surprises.

**Comment by Morl99** [comment] 2024-11-13 23:40
Thank you for letting us know. The root cause is the following upstream change: https://github.com/bitnami/containers/issues/74788

The next build will fix this, so I expect this to be fixed in the next few hour.

I appreciate your idea about pinning, but it will take a bit or effort to do that due to the nature of the multi-version actions. Since this was the first time this happened, and it was fixed fast, we will not put any effort in pinning versions. Feel free to pin our image digest if you use it, it will shield you from problems like this going into production.

I would welcome MRs that work toward a pin though, even if it only starts with some simple tests in the action, which would also be enough to catch errors like this.

**Comment by Morl99** [comment] 2024-11-13 23:42
I have just retriggered a new build which fixed the issue.

**Closed** 2024-11-13 23:42 UTC
